version: '3.9'

volumes:
  poetry-cache:

services:
  dash:
    build:
      context: .
      target: dev
    image: plotly-dash-app
    environment:
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "80"
      FLASK_ENV: development
      FLASK_DEBUG: 1
    ports:
    - "127.0.0.1:8050:80"
    volumes:
    - .:/dash
    - poetry-cache:/opt/.cache
